### ISSUE TITLE
renogy dcc50s bt-2  modbus exception

### ISSUE THREAD

**Issue by riker65** [wildmountainfarms/solarthing#29]
Hi 
Iwas testing the renogy Bluetooth module bt-2

having a requestion,

once connected the BT-2  to the renogy I had an issue with other serial readings

I do not get any serial data when bt was disconnected again?
Modbus exception error. no answer

have you experienced something like this?

Thanks T

**Comment by retrodaredevil** [comment]
It is likely that the bt module changed the rovers modbus address. It commonly changes it to 16, so in your base.json, try setting `modbus` to 16. If that doesn't work, I can run the `rover-setup` program and run `scan 1 20`. It will take a while, but it should show you what address it has. 

You should also be able to change the address back to 1 in the app somehow. 

I assume your error is a modbus timeout exception? If it's not, then posting the error would be helpful.

**Comment by riker65** [comment]
thanks for the hint
will check for new adress with the scan.

i thought something like this an tried address 2 already . will check for 16 and scan.

Perfect thanks

**Comment by retrodaredevil** [comment]
It just occurred to me that the scan feature is not a part of SolarThing 2021.3.0, so you can try to find the address manually, compile SolarThing yourself and use scan, or wait for me to update it.

**Comment by retrodaredevil** [comment]
SolarThing 2021.3.1 has the scan feature. You can update if you'd like, but there aren't any new features I'm aware of that will benefit you.

Close this if you get it working.

**Comment by riker65** [comment]
Hi 
thanks just updated

but how to run `scan 1 20`"?

**Comment by riker65** [comment]
Hi Joshua,

found the scan feature. but where do i get the result from?
`
Scan finished!

scan 1 20
Starting scan. (Will tell you when scan has stopped)
}`

thanks

**Comment by riker65** [comment]
Hi Joshua,

I found new slave address at hex 0x60/dec 96  confirmed by renogy support
given by BT-2 connection

Thanks for your support

**Comment by retrodaredevil** [comment]
Huh. That's really weird that it decided it wanted an address of 96. If I have to recommend that people scan from 1 to 247, that's gonna take a long time.

>  Scan finished!

If there was nothing between this message and the "scan started" message, it means it didn't find a rover, which makes sense because it was on an address outside the range you were scanning.

I probably need to figure out a way to do a quicker scan. 2 seconds per address isn't really acceptable if it's address can be in a large range of addresses.

I guess I'll probably recommend try to find their address through their BT module from now on lol.
