### ISSUE TITLE
modbus ser2net

### ISSUE THREAD

**Issue by riker65** [wildmountainfarms/solarthing#60]
Hi,

I am wondering if you have used ser2net to send modbus data to another server?

My RPI is kind of weak for all, so I would migrate it to a more powerfull server.

Thanks for hints

would it be possible to use a ser2net port in solarthing base.json config?

Thomas

**Comment by retrodaredevil** [comment]
I personally don't have any experience with ser2net. I also don't recommend doing something like this because SolarThing can run just fine on Raspberry Pis, but I do recommend that the database be put on another computer.

If ser2net exposes a serial port similar to what `socat` does, then I imagine you could treat whatever ser2net gives you as a serial port. If it does not do that, then I likely won't add support for ser2net integration, but if you still want to continue along this path, you could see this issue for reference on how this might be done: https://github.com/wildmountainfarms/solarthing/issues/51

**Comment by riker65** [comment]
ok thanks will check

**Comment by riker65** [comment]
closed socat should be used
